### ISSUE TITLE
Unable to install cucumber version 0.0.24

### ISSUE THREAD

**Issue by Aswini999** [masterthought/jenkins-cucumber-jvm-reports-plugin-java#119]
Hi,
Currently I'm having issues with report generation when different json files are present in the folder. 
Cucumber-reports version is 0.0.23. I tried installing 0.0.24 in jenkins but failed. 
Can you please help me in installing the new version?
Also,  can i know the reason why I'm not able to see the cucumber-reports 0.0.24 in the updates list.
Is there any restriction with the jenkins version(we are in jenkins version: 1.589).

Please revert back as soon as possible

**Comment by kingsleyh** [comment]
I may have forgotten to update the label when I deployed. I'm going to release again in the next couple of days

**Comment by aiman-alsari** [comment]
Hi @kingsleyh , just to let you know that I'm very keen to get my hands on 0.0.24 as well. The addition of file{Include,Exclude}Pattern would be very beneficial.

**Comment by Aswini999** [comment]
Hi @kingsleyh , Is there any update regarding this as we are in very much need of it.

**Comment by kingsleyh** [comment]
Just released it again

**Comment by Aswini999** [comment]
Still I'm not able to see the updated version in jenkins. Please refer the screenshot attached
![cucumber_jenkins](https://cloud.githubusercontent.com/assets/5479114/7003920/5f8ba162-dc80-11e4-98a0-71a8969c912a.png)

**Comment by kingsleyh** [comment]
That page doesn't seem to have been updated yet - but when I released it this morning it got pushed here:

http://maven.jenkins-ci.org:8081/content/repositories/releases/net/masterthought/jenkins/cucumber-reports/0.0.24/ <http://maven.jenkins-ci.org:8081/content/repositories/releases/net/masterthought/jenkins/cucumber-reports/0.0.24/>

so I assume at some point it will make it's way onto that page you sent me.

--K

**Comment by kingsleyh** [comment]
Ah at the very bottom of this page: https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org <https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org>

point 2 - says that the update-center.json is updated every 6 hours. So that's probably the delay.

--K

**Comment by Aswini999** [comment]
@kingsleyh, Thank you so much... There was a delay and it is updated after sometime. 
Note: Link to wiki page is not valid. So it is redirecting to 404 after plugin is installed
