### ISSUE TITLE
Broken report generation

### ISSUE THREAD

**Issue by aeells** [masterthought/jenkins-cucumber-jvm-reports-plugin-java#124]
I have plugin version 0.0.24 installed (the screenshot is incorrectly reporting this) in Jenkins 1.605 and an acceptance test running with cucumber-junit dependencies as below:

            <dependency>
                <groupId>info.cukes</groupId>
                <artifactId>cucumber-java</artifactId>
                <version>1.2.2</version>
            </dependency>
            <dependency>
                <groupId>info.cukes</groupId>
                <artifactId>cucumber-junit</artifactId>
                <version>1.2.2</version>
            </dependency>

Whilst the test executes and passes in Jenkins, the plugin is not generating the correct HTML output with the following exception (screenshot also attached):

    org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getRawName' in 
    class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at 
    templates/featureOverview.vm[line 366, column 31]

![screen shot 2015-04-20 at 15 56 51](https://cloud.githubusercontent.com/assets/266527/7233139/741d2d10-e777-11e4-9b08-3891461c53b6.png)

**Comment by kingsleyh** [comment]
Could you send me your json? Kingsley at masterthought dot net

**Comment by aeells** [comment]
On it's way Kingsley.
Many thanks, Andrew

**Comment by aeells** [comment]
hello again @kingsleyh, 

so having played around a bit more i’ve realised this issue is because i have a multi-module maven project and had not set the 'Json Reports Path’ properly. pointing it at the 'acceptance-tests/target' dir means it's now running fine and i'll close the issue.

thanks and regards, andrew
