### ISSUE TITLE
Json file not coping to workspace folder

### ISSUE THREAD

**Issue by HGill1** [masterthought/jenkins-cucumber-jvm-reports-plugin-java#127]
When I am running the build I am getting this error in Jenkins console 

[CucumberReportPublisher] there were no json results found in: C:\Users\~\.jenkins\jobs\myproject\workspace\
[CucumberReportPublisher] there were no json results found in: C:\Users\~\.jenkins\jobs\myproject\builds\21\cucumber-html-reports

I am using 0.0.24 library and using 1.2.0 cucumber version and my test runner file is like this

@RunWith(Cucumber.class)
@CucumberOptions(
plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json"},
features = {"src/cucumber"}
)
public class TestRunner {

}

In Jenkins cucumber report configuration I tried the following

Json Reports Path : target , / and left empty

For plugin URL path I left it empty.

Though cucumber.json report is there in my project target folder but its not coping to Jenkins workspace folder when I run the build. I have to manually copy the .json file and then rerun the build then it displays the reports.

**Comment by HGill1** [comment]
I have fixed it the path I was giving inside my cucumberOptions should be the path of workspace.

**Comment by quangtringuyen** [comment]
I am facing with the same issue. Can you please let me know how can I resolve the problem. Now I can work around like specify target folder exactly like: Json Reports Path: D:\Workspace\Test\cucumber-jvm-template-master\target
Is it correct?

@damianszczepanik Can you please comment also?
